-- FijiBoundless — Expanded Locations Dataset
-- 50 real Fiji locations across all four divisions, with accessibility
-- assessments and seed verifications. IDs continue on from seed.sql (1-7).
-- Run: wrangler d1 execute fijiboundless --local  --file=database/locations.sql
-- Run: wrangler d1 execute fijiboundless --remote --file=database/locations.sql

-- ── Facilities ────────────────────────────────────────────────────────────────
INSERT OR IGNORE INTO facilities (id, name, category, division, island, town_or_area, address, lat, lng) VALUES
-- Western Division
(8,  'Sheraton Fiji Resort',                   'hotel',      'Western', 'Viti Levu',      'Denarau',       'Denarau Island, Nadi',                -17.7810, 177.3850),
(9,  'Westin Denarau Island Resort & Spa',      'hotel',      'Western', 'Viti Levu',      'Denarau',       'Denarau Island, Nadi',                -17.7820, 177.3862),
(10, 'Hilton Fiji Beach Resort & Spa',          'hotel',      'Western', 'Viti Levu',      'Denarau',       'Denarau Island, Nadi',                -17.7830, 177.3870),
(11, 'Radisson Blu Resort Fiji Denarau Island', 'hotel',      'Western', 'Viti Levu',      'Denarau',       'Denarau Island, Nadi',                -17.7795, 177.3825),
(12, 'Tanoa International Hotel',               'hotel',      'Western', 'Viti Levu',      'Nadi',          'Votualevu Rd, Nadi',                  -17.7813, 177.4436),
(13, 'Musket Cove Island Resort',                'hotel',      'Western', 'Malolo Lailai',  'Mamanuca Group','Malolo Lailai Island',                -17.7767, 177.1928),
(14, 'Castaway Island Fiji',                     'hotel',      'Western', 'Castaway Island','Mamanuca Group','Castaway Island',                     -17.6425, 177.1844),
(15, 'InterContinental Fiji Golf Resort & Spa',  'hotel',      'Western', 'Viti Levu',      'Natadola',      'Maro Rd, Natadola, Sigatoka',         -18.1928, 177.3653),
(16, 'Natadola Beach',                           'beach',      'Western', 'Viti Levu',      'Natadola',      'Natadola, Sigatoka',                  -18.1917, 177.3667),
(17, 'Wailoaloa Beach (Newtown Beach)',          'beach',      'Western', 'Viti Levu',      'Nadi',          'Wailoaloa Rd, Newtown, Nadi',         -17.7863, 177.3939),
(18, 'Momi Bay Beach',                           'beach',      'Western', 'Viti Levu',      'Momi',          'Momi Bay, Nadi',                      -17.9350, 177.2800),
(19, 'Sabeto Hot Springs & Mud Pool',            'attraction', 'Western', 'Viti Levu',      'Sabeto',        'Sabeto Rd, Nadi',                     -17.7015, 177.4685),
(20, 'Sri Siva Subramaniya Temple',              'attraction', 'Western', 'Viti Levu',      'Nadi',          'Nadi Back Rd, Nadi Town',             -17.8065, 177.4198),
(21, 'Saffron Restaurant',                       'restaurant', 'Western', 'Viti Levu',      'Nadi',          'Tanoa International Hotel, Nadi',     -17.7813, 177.4436),
(22, 'Nadina Authentic Fijian Restaurant',       'restaurant', 'Western', 'Viti Levu',      'Nadi',          'Northern Press Rd, Namaka, Nadi',     -17.7825, 177.4380),
(23, 'Vuda Point Marina',                        'ferry',      'Western', 'Viti Levu',      'Vuda',          'Vuda Point, Lautoka',                 -17.6667, 177.3500),
(24, 'Port Denarau Marina Ferry Terminal',       'ferry',      'Western', 'Viti Levu',      'Denarau',       'Port Denarau, Nadi',                  -17.7730, 177.3843),
(25, 'Navala Village',                           'village',    'Western', 'Viti Levu',      'Ba',            'Navala, Ba Highlands',                -17.7333, 177.7333),
-- Central Division
(26, 'Grand Pacific Hotel',                      'hotel',      'Central', 'Viti Levu',      'Suva',          'Victoria Parade, Suva',               -18.1416, 178.4247),
(27, 'Holiday Inn Suva',                         'hotel',      'Central', 'Viti Levu',      'Suva',          'Victoria Parade, Suva',               -18.1420, 178.4300),
(28, 'Novotel Suva Lami Bay',                    'hotel',      'Central', 'Viti Levu',      'Lami',          'Queens Rd, Lami',                     -18.1167, 178.4167),
(29, 'Uprising Beach Resort',                    'hotel',      'Central', 'Viti Levu',      'Pacific Harbour','Wainiyabia, Pacific Harbour',        -18.2350, 178.1900),
(30, 'Beqa Lagoon Resort',                       'hotel',      'Central', 'Beqa Island',    'Beqa Island',   'Beqa Island',                          -18.4000, 178.1500),
(31, 'Colo-i-Suva Forest Park',                  'attraction', 'Central', 'Viti Levu',      'Colo-i-Suva',   'Princes Rd, Colo-i-Suva',             -18.0333, 178.4500),
(32, 'Fiji Museum',                              'attraction', 'Central', 'Viti Levu',      'Suva',          'Thurston Gardens, Suva',              -18.1372, 178.4239),
(33, 'Kula Wild Adventure Park',                 'attraction', 'Central', 'Viti Levu',      'Pacific Harbour','Queens Rd, Pacific Harbour',         -18.2394, 178.1519),
(34, 'Tiko''s Floating Restaurant',              'restaurant', 'Central', 'Viti Levu',      'Suva',          'Stinson Parade, Suva Harbour',        -18.1420, 178.4270),
(35, 'Old Mill Cottage',                         'restaurant', 'Central', 'Viti Levu',      'Suva',          'Carnarvon St, Suva',                  -18.1394, 178.4258),
(36, 'Suva Wharf (Kings Wharf)',                 'ferry',      'Central', 'Viti Levu',      'Suva',          'Kings Wharf Rd, Walu Bay, Suva',      -18.1350, 178.4310),
(37, 'Natovi Landing',                           'ferry',      'Central', 'Viti Levu',      'Tailevu',       'Natovi, Tailevu',                     -17.7167, 178.5667),
(38, 'Namuamua Village',                         'village',    'Central', 'Viti Levu',      'Namosi',        'Namuamua, Namosi',                    -18.0000, 178.1500),
(39, 'Pacific Harbour Beach',                    'beach',      'Central', 'Viti Levu',      'Pacific Harbour','Pacific Harbour',                    -18.2333, 178.1833),
-- Northern Division
(40, 'Jean-Michel Cousteau Resort',              'hotel',      'Northern','Vanua Levu',     'Savusavu',      'Lesiaceva Point Rd, Savusavu',        -16.7500, 179.3667),
(41, 'Koro Sun Resort',                          'hotel',      'Northern','Vanua Levu',     'Savusavu',      'Hibiscus Hwy, Savusavu',              -16.7333, 179.4000),
(42, 'Paradise Taveuni',                         'hotel',      'Northern','Taveuni',        'Taveuni',       'Taveuni Island',                      -16.8167, 179.9667),
(43, 'Bouma National Heritage Park',             'attraction', 'Northern','Taveuni',        'Bouma',         'Bouma, Taveuni',                      -16.7667, 179.9167),
(44, 'Naag Mandir Temple',                       'attraction', 'Northern','Vanua Levu',     'Labasa',        'Labasa',                              -16.4322, 179.3672),
(45, 'Savusavu Wharf (Copra Shed Marina)',       'ferry',      'Northern','Vanua Levu',     'Savusavu',      'Copra Shed Marina, Savusavu',         -16.7778, 179.3372),
(46, 'Taveuni Wharf (Waiyevo)',                  'ferry',      'Northern','Taveuni',        'Waiyevo',       'Waiyevo, Taveuni',                    -16.8167, 179.9833),
(47, 'Lavena Village',                           'village',    'Northern','Taveuni',        'Lavena',        'Lavena Coastal Walk, Taveuni',        -16.8167, 179.9500),
(48, 'Naveria Heights Restaurant',               'restaurant', 'Northern','Vanua Levu',     'Savusavu',      'Naveria Heights Rd, Savusavu',        -16.7700, 179.3300),
(49, 'Lesiaceva Point Beach',                    'beach',      'Northern','Vanua Levu',     'Savusavu',      'Lesiaceva Point, Savusavu',           -16.8000, 179.3000),
-- Eastern Division
(50, 'Royal Hotel Levuka',                       'hotel',      'Eastern', 'Ovalau',         'Levuka',        'Beach St, Levuka',                    -17.6833, 178.8333),
(51, 'Matava Eco Resort',                        'hotel',      'Eastern', 'Kadavu',         'Kadavu',        'Kadavu Island',                       -19.0800, 178.1600),
(52, 'Levuka Historical Port Town',               'attraction', 'Eastern', 'Ovalau',         'Levuka',        'Beach St, Levuka',                    -17.6833, 178.8333),
(53, 'Cession Site & Nasau Park',                'attraction', 'Eastern', 'Ovalau',         'Levuka',        'Beach St, Levuka',                    -17.6822, 178.8339),
(54, 'Levuka Wharf',                             'ferry',      'Eastern', 'Ovalau',         'Levuka',        'Wharf St, Levuka',                    -17.6811, 178.8319),
(55, 'Vunisea Beach',                            'beach',      'Eastern', 'Kadavu',         'Vunisea',       'Vunisea, Kadavu',                     -19.0578, 178.1572),
(56, 'Lovoni Village',                           'village',    'Eastern', 'Ovalau',         'Lovoni',        'Lovoni Valley, Ovalau',               -17.6667, 178.8000),
(57, 'Whale''s Tale Restaurant',                 'restaurant', 'Eastern', 'Ovalau',         'Levuka',        'Beach St, Levuka',                    -17.6828, 178.8331);

-- ── Accessibility Features ────────────────────────────────────────────────────
INSERT OR IGNORE INTO accessibility_features
  (facility_id, step_free_entry, door_width_cm, accessible_parking, hoisting_equipment,
   pool_hoist, beach_wheelchair_available, all_terrain_wheelchair, grab_rails,
   roll_under_sink, shower_chair, sensory_friendly_rating, noise_level_rating,
   braille_signage, hearing_loop, boat_accessible, boat_notes)
VALUES
(8,  1, 90,   1, 1, 1, 1, 0, 1, 1, 1, 3, 3, 0, 0, 0, NULL),
(9,  1, 92,   1, 1, 1, 1, 0, 1, 1, 1, 3, 3, 0, 0, 0, NULL),
(10, 1, 90,   1, 1, 1, 1, 0, 1, 1, 1, 3, 2, 0, 1, 0, NULL),
(11, 1, 88,   1, 1, 1, 1, 0, 1, 1, 0, 3, 3, 0, 0, 0, NULL),
(12, 1, 85,   1, 0, 1, 0, 0, 1, 1, 0, 3, 2, 0, 0, 0, NULL),
(13, 0, 80,   1, 0, 1, 1, 1, 1, 1, 0, 4, 2, 0, 0, 1, 'Boat transfer from Denarau; small swell can make wheelchair transfer difficult at low tide.'),
(14, 0, 78,   0, 0, 0, 1, 1, 0, 1, 0, 4, 2, 0, 0, 1, '20-minute boat transfer from Denarau; resort buggies available on sand paths.'),
(15, 1, 92,   1, 1, 1, 1, 0, 1, 1, 1, 4, 2, 0, 0, 0, NULL),
(16, 0, NULL, 1, 0, 0, 1, 1, 0, 0, 0, 4, 3, 0, 0, 0, NULL),
(17, 0, NULL, 0, 0, 0, 1, 0, 0, 0, 0, 3, 3, 0, 0, 0, NULL),
(18, 0, NULL, 1, 0, 0, 0, 1, 0, 0, 0, 4, 2, 0, 0, 0, NULL),
(19, 0, 85,   1, 0, 0, 0, 1, 0, 1, 0, 3, 3, 0, 0, 0, NULL),
(20, 1, 90,   1, 0, 0, 0, 0, 1, 0, 0, 2, 3, 0, 0, 0, NULL),
(21, 1, 88,   1, 0, 0, 0, 0, 0, 1, 0, 3, 3, 0, 0, 0, NULL),
(22, 1, 82,   1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, NULL),
(23, 0, NULL, 1, 0, 0, 0, 1, 0, 0, 0, 3, 2, 0, 0, 1, 'Pontoon gangway gradient increases significantly at low tide; staff assist with advance notice.'),
(24, 1, 120,  1, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 1, 'Floating pontoons for Yasawa/Mamanuca ferries; gangway gradient varies with tide, staff assistance offered.'),
(25, 0, NULL, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 0, NULL),
(26, 1, 95,   1, 1, 1, 0, 0, 1, 1, 1, 3, 3, 1, 1, 0, NULL),
(27, 1, 90,   1, 1, 1, 0, 0, 1, 1, 1, 3, 3, 0, 0, 0, NULL),
(28, 1, 90,   1, 0, 1, 0, 0, 1, 1, 0, 4, 2, 0, 0, 0, NULL),
(29, 0, 82,   1, 0, 1, 1, 1, 1, 1, 0, 4, 2, 0, 0, 0, NULL),
(30, 0, 80,   0, 0, 0, 1, 1, 0, 1, 0, 4, 1, 0, 0, 1, 'Boat transfer only, ~45 min from Pacific Harbour; calm lagoon crossing, staff assist boarding.'),
(31, 0, NULL, 1, 0, 0, 0, 1, 0, 0, 0, 4, 2, 0, 0, 0, NULL),
(32, 1, 92,   1, 0, 0, 0, 0, 1, 1, 0, 3, 3, 1, 0, 0, NULL),
(33, 1, 90,   1, 0, 0, 0, 1, 0, 1, 0, 3, 2, 0, 0, 0, NULL),
(34, 0, 80,   0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 1, 'Fixed gangway to floating pontoon restaurant; manageable in calm conditions, difficult in swell.'),
(35, 1, 78,   0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, NULL),
(36, 0, NULL, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 'Inter-island ferry terminal; ramps present but steep, high foot traffic on departure days.'),
(37, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 1, 'Basic landing point for Ovalau/Vanua Levu ferries; no formal ramp, staff assist with boarding.'),
(38, 0, NULL, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 1, 'Reached by river punt from Navua; village paths are grass and uneven, all-terrain wheelchair recommended.'),
(39, 0, NULL, 1, 0, 0, 1, 1, 0, 0, 0, 4, 2, 0, 0, 0, NULL),
(40, 1, 88,   1, 1, 1, 1, 0, 1, 1, 1, 4, 2, 0, 0, 0, NULL),
(41, 0, 82,   1, 0, 1, 1, 1, 1, 1, 0, 4, 2, 0, 0, 0, NULL),
(42, 0, 80,   1, 0, 1, 1, 1, 1, 1, 0, 4, 1, 0, 0, 1, 'Remote dive resort; boat and 4WD transfer from Taveuni Wharf, uneven garden paths.'),
(43, 0, NULL, 1, 0, 0, 0, 1, 0, 0, 0, 4, 2, 0, 0, 0, NULL),
(44, 1, 90,   1, 0, 0, 0, 0, 1, 0, 0, 2, 3, 0, 0, 0, NULL),
(45, 0, NULL, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 'Floating marina walkway; gradient changes with tide, no dedicated hoist.'),
(46, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 'Small inter-island wharf; concrete ramp present but no rails, assistance from crew usual.'),
(47, 0, NULL, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 0, NULL),
(48, 0, 80,   1, 0, 0, 0, 0, 0, 1, 0, 4, 1, 0, 0, 0, NULL),
(49, 0, NULL, 0, 0, 0, 1, 0, 0, 0, 0, 4, 1, 0, 0, 0, NULL),
(50, 0, 78,   0, 0, 0, 0, 0, 0, 1, 0, 3, 2, 0, 0, 0, NULL),
(51, 0, 75,   0, 0, 0, 1, 1, 0, 1, 0, 4, 1, 0, 0, 1, 'Boat transfer from Vunisea, ~40 min; eco-resort on stilts with timber walkways, not step-free.'),
(52, 1, NULL, 1, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, NULL),
(53, 1, NULL, 1, 0, 0, 0, 0, 0, 0, 0, 4, 2, 0, 0, 0, NULL),
(54, 0, NULL, 1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 1, 'Small town wharf servicing Suva ferry; concrete ramp, moderate gradient, no rails.'),
(55, 0, NULL, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 0, NULL),
(56, 0, NULL, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 0, NULL),
(57, 1, 85,   1, 0, 0, 0, 0, 0, 1, 0, 3, 3, 0, 0, 0, NULL);

-- ── Verifications ─────────────────────────────────────────────────────────────
-- verified_at uses relative offsets so freshness badges stay meaningful over time.
INSERT OR IGNORE INTO verifications (facility_id, verified_by, verifier_name, verified_at, status, notes) VALUES
(8,  'staff',     'FijiBoundless Field Team',      datetime('now', '-12 days'),  'verified',     'Step-free from lobby to beachfront. Pool hoist available on request via guest services.'),
(9,  'staff',     'FijiBoundless Field Team',      datetime('now', '-18 days'),  'verified',     'Accessible rooms on ground floor near lifts. Beach access via boardwalk.'),
(10, 'partner',   'Hilton Fiji Accessibility Desk', datetime('now', '-25 days'), 'verified',     'Two adapted rooms with roll-in shower. Hearing loop fitted in main conference room.'),
(11, 'staff',     'FijiBoundless Field Team',      datetime('now', '-40 days'),  'verified',     'Ramped entry from valet drop-off. Pool hoist stored at pool bar, ask attendant.'),
(12, 'staff',     'FijiBoundless Field Team',      datetime('now', '-55 days'),  'verified',     'Ground floor rooms available; no pool hoist on site.'),
(13, 'partner',   'Musket Cove Guest Services',    datetime('now', '-70 days'),  'verified',     'Boat transfer required; advise ahead for wheelchair boarding assistance at Denarau.'),
(14, 'community', 'Ana R.',                        datetime('now', '-95 days'),  'needs_update', 'Sand paths hard to navigate in a standard wheelchair; resort buggy helps but not confirmed for larger chairs.'),
(15, 'staff',     'FijiBoundless Field Team',      datetime('now', '-8 days'),   'verified',     'Fully accessible golf resort with ocean-view rooms and pool hoist.'),
(16, 'community', 'Mosese V.',                     datetime('now', '-30 days'),  'verified',     'Beach wheelchair available free from the lifeguard hut on weekends.'),
(17, 'community', 'Litia B.',                      datetime('now', '-110 days'), 'needs_update', 'No formal accessible path from car park to sand; loose gravel.'),
(18, 'staff',     'FijiBoundless Field Team',      datetime('now', '-60 days'),  'verified',     'Calm bay, popular with families; beach wheelchair not yet available on site.'),
(19, 'staff',     'FijiBoundless Field Team',      datetime('now', '-20 days'),  'needs_update', 'Mud pool area has uneven, slippery ground; hot spring pools have steps only.'),
(20, 'community', 'Priya S.',                      datetime('now', '-15 days'),  'verified',     'Ramp added at main entrance in 2025. Ground-floor circuit around the temple is step-free.'),
(21, 'staff',     'FijiBoundless Field Team',      datetime('now', '-18 days'),  'verified',     'Step-free from hotel lobby. Tables can be rearranged for wheelchair users on request.'),
(22, 'community', 'Josefa T.',                     datetime('now', '-50 days'),  'verified',     'Step-free entrance; can be loud during evening meke shows.'),
(23, 'partner',   'Vuda Point Marina Office',      datetime('now', '-33 days'),  'needs_update', 'Pontoon gangway gradient increases significantly at low tide; check tide times before boarding.'),
(24, 'staff',     'FijiBoundless Field Team',      datetime('now', '-5 days'),   'verified',     'Main terminal building step-free; floating pontoons to boats vary with tide, staff assist available.'),
(25, 'community', 'Bulou N.',                      datetime('now', '-140 days'), 'needs_update', 'Traditional village on sloped terrain; chief''s approval and sevusevu required before visiting.'),
(26, 'staff',     'FijiBoundless Field Team',      datetime('now', '-22 days'),  'verified',     'Heritage hotel fully retrofitted; lift access to all guest floors.'),
(27, 'staff',     'FijiBoundless Field Team',      datetime('now', '-28 days'),  'verified',     'Step-free entry from Victoria Parade; accessible rooms on request.'),
(28, 'staff',     'FijiBoundless Field Team',      datetime('now', '-45 days'),  'verified',     'Ground floor rooms overlook Lami Bay; no pool hoist.'),
(29, 'community', 'Anare K.',                      datetime('now', '-80 days'),  'needs_update', 'Timber walkways between bures have some raised thresholds.'),
(30, 'partner',   'Beqa Lagoon Resort',            datetime('now', '-65 days'),  'verified',     'Resort designed with wide bure doorways; boat transfer assistance included.'),
(31, 'community', 'Sera M.',                       datetime('now', '-100 days'), 'needs_update', 'Main pool viewing area reachable on packed dirt path; the swimming hole itself requires steps.'),
(32, 'staff',     'FijiBoundless Field Team',      datetime('now', '-10 days'),  'verified',     'Fully step-free museum galleries; accessible restroom near entrance.'),
(33, 'staff',     'FijiBoundless Field Team',      datetime('now', '-38 days'),  'verified',     'Boardwalk circuit suitable for wheelchairs; some animal enclosures have raised viewing decks.'),
(34, 'community', 'Ravin P.',                      datetime('now', '-75 days'),  'needs_update', 'Fixed gangway to the pontoon restaurant can be steep; best visited at high tide.'),
(35, 'community', 'Elenoa W.',                     datetime('now', '-120 days'), 'needs_update', 'Charming heritage cottage but the doorway is narrower than modern standard.'),
(36, 'staff',     'FijiBoundless Field Team',      datetime('now', '-14 days'),  'needs_update', 'Main terminal accessible; boarding ramps to inter-island ferries are steep and unassisted.'),
(37, 'community', 'Petero D.',                     datetime('now', '-150 days'), 'needs_update', 'Informal landing point; no ramp, request crew assistance in advance.'),
(38, 'community', 'Ilisapeci R.',                  datetime('now', '-160 days'), 'needs_update', 'River access only via traditional punt; village paths grass and uneven after rain.'),
(39, 'staff',     'FijiBoundless Field Team',      datetime('now', '-48 days'),  'verified',     'Popular family beach with calm shallows; beach wheelchair available seasonally.'),
(40, 'partner',   'Jean-Michel Cousteau Resort',   datetime('now', '-16 days'),  'verified',     'Purpose-built accessible bungalow with roll-in shower and pool hoist.'),
(41, 'community', 'Waisea L.',                     datetime('now', '-90 days'),  'needs_update', 'Hillside resort with steps between levels; ground-floor bures more accessible.'),
(42, 'partner',   'Paradise Taveuni',              datetime('now', '-85 days'),  'needs_update', 'Remote dive resort; garden paths uneven, best suited to ambulatory guests with assistance.'),
(43, 'staff',     'FijiBoundless Field Team',      datetime('now', '-42 days'),  'needs_update', 'Lower Tavoro waterfall has a short boardwalk; the upper falls require a steep, uneven trail.'),
(44, 'community', 'Vimal K.',                      datetime('now', '-55 days'),  'verified',     'Large open temple grounds, step-free from car park to main shrine.'),
(45, 'partner',   'Copra Shed Marina',             datetime('now', '-35 days'),  'needs_update', 'Floating walkway to boats shifts with tide; staff on hand during business hours.'),
(46, 'staff',     'FijiBoundless Field Team',      datetime('now', '-170 days'), 'needs_update', 'Small wharf serving the Suva ferry; concrete ramp present, no handrails yet.'),
(47, 'community', 'Ateca F.',                      datetime('now', '-130 days'), 'needs_update', 'Start of the Lavena Coastal Walk; the village itself is flat but the onward trail is not wheelchair accessible.'),
(48, 'community', 'Mere S.',                       datetime('now', '-60 days'),  'needs_update', 'Beautiful hillside views but several steps up to the main dining deck.'),
(49, 'community', 'Joeli N.',                      datetime('now', '-145 days'), 'verified',     'Quiet peninsula beach, calm water, informal sandy access from the road.'),
(50, 'community', 'Rupeni V.',                     datetime('now', '-190 days'), 'needs_update', 'Fiji''s oldest hotel; heritage timber verandas with narrow doorways, charming but not step-free.'),
(51, 'partner',   'Matava Eco Resort',             datetime('now', '-70 days'),  'needs_update', 'Eco-resort built on stilts with timber walkways; not step-free but staff assist throughout.'),
(52, 'staff',     'FijiBoundless Field Team',      datetime('now', '-20 days'),  'verified',     'Flat, walkable heritage town centre along Beach Street.'),
(53, 'staff',     'FijiBoundless Field Team',      datetime('now', '-20 days'),  'verified',     'Level parkland with paved paths around the cession monument.'),
(54, 'community', 'Timoci B.',                     datetime('now', '-155 days'), 'needs_update', 'Small town wharf; ramp present but steep for unassisted use.'),
(55, 'community', 'Litiana C.',                    datetime('now', '-165 days'), 'verified',     'Calm, quiet beach near Vunisea airstrip; informal access.'),
(56, 'community', 'Kolinio T.',                    datetime('now', '-175 days'), 'needs_update', 'Crater village reached by unsealed road; community-guided tours recommended.'),
(57, 'community', 'Ana D.',                        datetime('now', '-40 days'),  'verified',     'Relaxed harbourside restaurant, step-free entrance from Beach Street.');
